### ISSUE TITLE
Refresh existing tokens

### ISSUE THREAD

**Issue by Megh-Thakkar** [wichert/pyramid_jwt#18]
It is an amazing implementation of token authentication. However I had a question regarding how do you refresh an existing token? I am new to pyramid and have worked extensively with `django`(and hence `djangorestframework-jwt`) before. Can you provide a code snippet for the same?  
Thanks.

**Comment by wichert** [comment]
There is no generic token-refresh standard. Basically this is something you need to implement as part of your API: you just need to add an endpoint (URL) which returns a new JWT token to the user. This could be something as simple as:

```python
@view_config(route_name='token-refresh', permission='view', renderer='json')
def refresh_token(request):
    token = request.create_jwt_token(request.authenticated_userid)
    return { 'token': token }
```

**Comment by rajib-raiyat** [comment]
I want to create a token during login that will expire in the 60's (1 minute) and I want to generate a refresh token with another API after login, which we can see in the [last comment](https://github.com/wichert/pyramid_jwt/issues/18#issuecomment-370146513). But this time I want the refresh token to expire within 3600s (1 hour).

However the problem is in the config file I can set the expiration time for both login and refresh tokens at ones. That means my login and refresh token will expire in the 60s (1 minute).

`config.set_jwt_authentication_policy ('incognito', auth_type = 'carrier', callback = add-action_related, expiration = 3600)`


Can I set the login and refresh the token expiration time separately?
