### ISSUE TITLE
Error decoding a token with audience claim

### ISSUE THREAD

**Issue by einarjohnson** [wichert/pyramid_jwt#19]
I'm getting a "Invalid audience" error from the pyramid_jwt lib. There is an audience section in the token:
```
{
"nbf": 1520083317,
"exp": 1520086917,
"iss": "https://demo.identityserver.io",
"aud": [
"https://demo.identityserver.io/resources",
"api"
],
"client_id": "client",
"scope": [
"api"
]
}
```
Can I somehow pass an audience param down to the decode method?

**Comment by wichert** [comment]
Can you provide the full stack trace ?

**Comment by einarjohnson** [comment]
the output I am seeing is:
`2018-03-05 13:07:51,260 WARNI [pyramid_jwt:67][waitress] Invalid JWT token from ::1: Invalid audience
2018-03-05 13:07:51,260 DEBUG [patientapi:349][waitress] debug_authorization of url http://localhost:6543/terms (view name '' against context <patientapi.RootACL object at 0x7f2899b6a668>): ACLDenied permission 'api' via ACE '<default deny>' in ACL [('Allow', 'admin', <pyramid.security.AllPermissionsList object at 0x7f28a0faf3c8>), ('Allow', 'api', ['api'])] on context <patientapi.RootACL object at 0x7f2899b6a668> for principals ['system.Everyone']
`

The token I use (generated from the demo.identityserver.io) is:
`eyJhbGciOiJSUzI1NiIsImtpZCI6IjI4NTY5ZTE3M2I0MGJiNGQ0ODNkZWIyNjBhYmQ5NGMwIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1MjAyNTUyMzYsImV4cCI6MTUyMDI1ODgzNiwiaXNzIjoiaHR0cHM6Ly9kZW1vLmlkZW50aXR5c2VydmVyLmlvIiwiYXVkIjpbImh0dHBzOi8vZGVtby5pZGVudGl0eXNlcnZlci5pby9yZXNvdXJjZXMiLCJhcGkiXSwiY2xpZW50X2lkIjoiY2xpZW50Iiwic2NvcGUiOlsiYXBpIl19.ph0VlZSND_KDADr8mg-IaKkj1fMSkPSCZk5jhitST3TInGddJ0BiYMkPOsOweGLoFgEuriuYgSEj3IuEqywDSPR1hIDxX_x45gBSAPqKHgN14NVIAMZeBPuYuyZ4xCG_m8mN0DsPUxhN2W3pf0xXqMMlde_t8DF1NiqnEDbsD9XYIG-33TBcIQQ7zExXOTWPmNf-q9t8JXdohoTPNS6N70yOL6VdKS58NiasVxI0__NWeyxmnJ1o_6XkFbN4Ftzdr42NSb6qEfHmzV1o8o0u4I1rJfSbQql1Rh0mOoNmiOL7xwxAqw0-XpGpx-R1v9MmPt-15aFHPlVIdieMAKzW1w`

**Comment by wichert** [comment]
Ok, looks like audience is something that pyramid-jwt does not support currently. Is this currently a hard requirement for you?

**Comment by wichert** [comment]
Note to self: [this is the relevant PyJWT documentation](http://pyjwt.readthedocs.io/en/latest/usage.html?highlight=decode#audience-claim-aud)

**Comment by einarjohnson** [comment]
hi, this is not really a hard requirement. I was just trying to get my framework up and running against something like IdentityServer4. to be honest, I am not even sure if we need a full fledged Oauth2 server for our project.  The idea is that the user logs in using a Login method in our REST API. This login method uses a mobile signature framework to verify the user. My idea was that the login method would then return a JWT token that would be used in subsequent calls.  Would I be gaining any additional security in using an IndentiyServer4 instead of just generating the JWT token from my Login method using pyramid_jwt (using assymetric methods of course)

**Comment by crooksey** [comment]
It takes just a few minutes and/or lines of code to implement your own JWT scheme, if using a Rest api (and you have the ability to add the JWT to the front end) it gives you total transparency (and no reliance to external libraries/servers) to manage your authentication. You can just extend your API to offer JWT authentication. 

JWT based authentication can be complex to get your head around, but once you understand it, its so simple and secure. The backend (pyramid) will detect any issues with the JWT (for example if someone tried a man in the middle attack) as long as your private key stays private and set a fairly secure timeout for the token, not a lot can go wrong, and it means any authentication code in the front end (which is accessible to anyone) can be exposed without any issues.

JWT + SSL and you are secure, especially as you can extend the token to offer exactly what you want/need in the way of permissions/extra claims.

**Comment by einarjohnson** [comment]
agreed. thanks a lot for your quick answers and input guys, really appreciate it.

**Comment by crooksey** [comment]
Thanks, I'll work on adding audience support to the prow this week.My EVA-L09. On O2.-------- Original Message --------Subject: Re: [wichert/pyramid_jwt] Error decoding a token with audience claim (#19)From: einarjohnson <notifications@github.com>To: wichert/pyramid_jwt <pyramid_jwt@noreply.github.com>CC: Luke Crooks <luke@crooksey.org>,Comment <comment@noreply.github.com>agreed. thanks a lot for your quick answers and input guys, really appreciate it.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/wichert/pyramid_jwt","title":"wichert/pyramid_jwt","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/wichert/pyramid_jwt"}},"updates":{"snippets":[{"icon":"PERSON","message":"@einarjohnson in #19: agreed. thanks a lot for your quick answers and input guys, really appreciate it."}],"action":{"name":"View Issue","url":"https://github.com/wichert/pyramid_jwt/issues/19#issuecomment-374765139"}}}Sent via Migadu.com, world's easiest email hosting>
