### ISSUE TITLE
request.authenticated_userid always return None

### ISSUE THREAD

**Issue by qwexvf** [wichert/pyramid_jwt#6]
request.authenticated_userid always return None

**Comment by webjunkie01** [comment]
Probably you're missing the Authorization header in your request. Try to test it with curl

curl --header 'Authorization: JWT TOKEN' api.server.com

**Comment by wichert** [comment]
There are a few reasons this can happen:

* You check request.authenticated_userid in a context factory or `__init__()` of a context object. Since authentication happens after context setup you can not use any authentication-related data at that point.
* Your view does not have a permission. Without a permission Pyramid will not perform any authentication, so authenticated_userid will be None.
* Authentication failed for some reason, for example an invalid or missing HTTP header.

Since this works for everyone else I'm closing this ticket.
